---
- name: reload facts
  setup: filter='*'

- name: Cyclops | Copy api check elasticsearchstatus
  template: src=elasticsearch_ElasticSearchStatus dest={{ cyclops.conf_dir }}/check_api_elasticsearchstatus
        owner=cyclops group=cyclops mode=0644
  when: elasticsearch_check_elasticsearchstatus
  notify:
    - Cyclops | host-set
